<?php

namespace AppBundle\Repository;

/**
 * AcounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcounterRepository extends \Doctrine\ORM\EntityRepository
{
}
